export const ACTION_UPDATE_SORT_BY = 'UPDATE_SORT_BY';
export const ACTION_UPDATE_LANGUAGE = 'UPDATE_LANGUAGE';
export const ACTION_UPDATE_COUNTRY = 'UPDATE_COUNTRY';
export const ACTION_UPDATE_CATEGORY = 'UPDATE_CATEGORY';
export const ACTION_REPLACE_NEWS_LIST = 'REPLACE_NEWS_LIST';
export const ACTION_APPEND_NEWS_LIST = 'APPEND_NEWS_LIST';